#- hosts: tag_role_awx:&tag_wlasciciel_szkolenie09:&tag_srodowisko_dev
- hosts: all

  tasks: 
  - set_fact:
      aaa: 1235 

  - ping:
      data: "{{ aaa }}"

  - name: "wykonaj modul shell"
    shell: date; whoami
